### ISSUE TITLE
User APIでのfollwer数が常に0

### ISSUE THREAD

**Issue by imtan** [ventus-inc/proto_blow#29]
`/api/username/tweet`で表示されるAPIでフォロワーがいるにもかかわらず`follower:0`と表示される

おそらく`/accounts/api/serializers.py`の一部が動作していない

**Comment by tsukukobaan** [comment]
https://github.com/ventus-inc/proto_blow/pull/36
修正しました。今後のTODOに「フォローされてる数」だけでなく「フォローしてる数」も入れる必要ありだね
