### ISSUE TITLE
リプライのリンクがトップ画面から以外飛べない

### ISSUE THREAD

**Issue by imtan** [ventus-inc/proto_blow#31]
リプライの@リンクが正しく動作していない模様です。

http://localhost:8000/profiles/aaa/profiles/aaa/

こんな感じのurlに飛ばされます

**Comment by tsukukobaan** [comment]
https://github.com/ventus-inc/proto_blow/commit/d8e1e5fcfe32fb0db4c73ef4dc241d6354389035
一時的な修正したが、productionではできないのでIssueは残しておきます
